# Escape a string for safe inclusion inside a C compiler -D"NAME=..." flag.
function Escape-CString {
  param([string]$Value)
  if ($null -eq $Value) { return "" }
  $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
  return $escaped
}

function Test-IsLikelyWslOrHyperVAddress {
  param([string]$IpAddress)
  # WSL2 / Hyper-V host NICs commonly land in 172.16.0.0/12
  if ($IpAddress -match '^172\.(1[6-9]|2[0-9]|3[0-1])\.') { return $true }
  if ($IpAddress -like '169.254.*') { return $true }
  return $false
}

# Resolve the LAN IPv4 address of this machine (prefer non-loopback Ethernet/Wi-Fi).
function Get-PreferredLanIPv4 {
  $candidates = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.IPAddress -notlike '127.*' -and
      $_.PrefixOrigin -ne 'WellKnown' -and
      $_.AddressState -eq 'Preferred' -and
      -not (Test-IsLikelyWslOrHyperVAddress $_.IPAddress)
    } |
    Sort-Object -Property InterfaceMetric

  if ($candidates) {
    return $candidates[0].IPAddress
  }

  # Fallback: any non-loopback preferred address
  $fallback = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.IPAddress -notlike '127.*' -and
      $_.AddressState -eq 'Preferred'
    } |
    Sort-Object -Property InterfaceMetric
  if ($fallback) {
    return $fallback[0].IPAddress
  }
  return $null
}

# Lists likely ESP32 USB serial ports (Espressif VID 303A).
function Get-EspUsbSerialPorts {
  Get-PnpDevice -Class Ports -Status OK -ErrorAction SilentlyContinue |
    Where-Object { $_.InstanceId -match 'VID_303A' } |
    ForEach-Object {
      if ($_.FriendlyName -match '(COM\d+)') { $Matches[1] }
    }
}

# Writes firmware/include/NetworkSeedSecrets.generated.h from env vars.
function Set-RoseeyesSeedBuildFlags {
  param(
    [switch]$RequireAgentIp,
    [string]$FirmwareIncludeDir = ""
  )

  $WifiSsid = $env:WIFI_SSID
  $WifiPass = $env:WIFI_PASS
  $AgentIp = $env:MICROROS_AGENT_IP

  if (-not $FirmwareIncludeDir) {
    $FirmwareIncludeDir = Join-Path (Split-Path -Parent $PSScriptRoot) "firmware\include"
    if (-not (Test-Path $FirmwareIncludeDir)) {
      $FirmwareIncludeDir = Join-Path $PSScriptRoot "..\firmware\include"
    }
  }

  Remove-Item Env:PLATFORMIO_BUILD_FLAGS -ErrorAction SilentlyContinue

  if (-not $WifiSsid -or -not $WifiPass) {
    if ($RequireAgentIp) {
      throw "WIFI_SSID and WIFI_PASS environment variables are required."
    }
    return $false
  }

  if (-not $AgentIp) {
    $AgentIp = Get-PreferredLanIPv4
  }
  if ($RequireAgentIp -and -not $AgentIp) {
    throw "MICROROS_AGENT_IP is not set and no LAN IPv4 could be detected."
  }
  if (-not $AgentIp) {
    $AgentIp = "0.0.0.0"
  }

  $AgentPort = 8888
  if ($env:MICROROS_AGENT_PORT) {
    $AgentPort = [int]$env:MICROROS_AGENT_PORT
  }

  $SsidEsc = Escape-CString $WifiSsid
  $PassEsc = Escape-CString $WifiPass
  $IpEsc = Escape-CString $AgentIp

  $generated = Join-Path $FirmwareIncludeDir "NetworkSeedSecrets.generated.h"
  $content = @(
    '#pragma once',
    "// Generated by Build-And-Upload scripts. Do not commit.",
    "#define WIFI_SSID_SEED `"$SsidEsc`"",
    "#define WIFI_PASS_SEED `"$PassEsc`"",
    "#define MICROROS_AGENT_IP_SEED `"$IpEsc`"",
    "#define MICROROS_AGENT_PORT_SEED $AgentPort"
  ) -join "`n"

  New-Item -ItemType Directory -Force -Path $FirmwareIncludeDir | Out-Null
  [System.IO.File]::WriteAllText($generated, $content + "`n")
  Write-Host "Wrote NVS seed header: $generated (SSID length=$($WifiSsid.Length), agent=$AgentIp`:$AgentPort)"
  return $true
}

# Maps base env name to manual/ota variant used by this PlatformIO version.
function Get-RoseeyesUploadEnvName {
  param(
    [Parameter(Mandatory = $true)][string]$EnvName,
    [string]$OtaIp = "",
    [switch]$ManualBootloader
  )
  if ($OtaIp) { return "${EnvName}_ota" }
  if ($ManualBootloader) { return "${EnvName}_manual" }
  return $EnvName
}

# Uploads via serial or espota (dedicated PlatformIO envs, no --project-option).
# Always uses -d ProjectDir so the caller's working directory is unchanged.
function Invoke-RoseeyesUpload {
  param(
    [Parameter(Mandatory = $true)][string]$Pio,
    [Parameter(Mandatory = $true)][string]$ProjectDir,
    [Parameter(Mandatory = $true)][string]$EnvName,
    [string]$Port = "COM16",
    [string]$OtaIp = "",
    [switch]$ManualBootloader
  )

  $uploadEnv = Get-RoseeyesUploadEnvName -EnvName $EnvName -OtaIp $OtaIp -ManualBootloader:$ManualBootloader

  if ($OtaIp) {
    Write-Host "OTA upload via env=$uploadEnv to $OtaIp ..."
    & $Pio run -d $ProjectDir -e $uploadEnv -t upload --upload-port $OtaIp
    return [int]$LASTEXITCODE
  }

  $espPorts = @(Get-EspUsbSerialPorts)
  if ($espPorts.Count -gt 0 -and ($espPorts -notcontains $Port)) {
    Write-Warning "Port $Port is not an Espressif USB device. Detected: $($espPorts -join ', ')"
  }

  Write-Host "Serial upload via env=$uploadEnv to $Port ..."
  if ($ManualBootloader) {
    Write-Host "Manual bootloader: hold B, tap R, release B, then press Enter."
    [void](Read-Host)
  } else {
    Write-Host "Auto-reset enabled (Arduino IDE style: 1200bps touch + wait for port)."
    Write-Host "Close Serial Monitor first. Fallback only if needed: -ManualBootloader"
  }

  & $Pio run -d $ProjectDir -e $uploadEnv -t upload --upload-port $Port
  $uploadExit = [int]$LASTEXITCODE
  if ($uploadExit -ne 0 -and -not $ManualBootloader) {
    Write-Host "First upload attempt exit=$uploadExit - retrying once after 2s..."
    Start-Sleep -Seconds 2
    $espPorts = @(Get-EspUsbSerialPorts)
    if ($espPorts.Count -eq 1) {
      $Port = $espPorts[0]
      Write-Host "Using re-detected port $Port"
    }
    & $Pio run -d $ProjectDir -e $uploadEnv -t upload --upload-port $Port
    $uploadExit = [int]$LASTEXITCODE
  }

  Write-Host "Upload finished with exit code $uploadExit"
  return $uploadExit
}
